# This workflow will build a golang project
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build exporter deb,rpm and tgz artifacts 

on: 
  push:
    # branches: [master]
    # TODO this combination logic of branch + tag is not working.
    tags:
       - v*

permissions:
  id-token: write
  actions: write
  contents: write

jobs:
      
    tar_job:
      runs-on: ubuntu-latest    
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: gzip tar files
          run: |
            gpg --version
